### PR TITLE
repair broken exception handling

### LINKED ISSUE #17: Throwing inside of virtual stack behaves unexpectedly
A problem that was introduced or at least exacerbated when the runtime was moved from the synchronous to the asynchronous model.

The ability to try/catch is severely impacted, which inhibits normal development. As it stands, any method that throws halts the entire stack and causes the root to throw:

```
const main = async () => {
  try{
    try{
      aFunctionThatThrows();
    }catch(e){
       /// Do somthing
    }
  handle default with (e){
    recall "great!"
  }
}

main().catch(e => console.log("This happens :(") )
```

This is major drawback, and needs to be fixed for effects to be usable

### PR DESCRIPTION
**Pull request by dpchamps**
## problem

In migrating the stack interpreter to async, a regression was introduced that impacted the way exceptions bubble through stack frames.

An exception that occured would effectively halt the entire stack, causing the exception to eject at the root of the invocation, instead of being handled appropriately by try/catch boundaries.

## solution

`unwindStack` more appropriately `throws` into parent generator functions from children that are currently throwing.

closes #17

### CODE REVIEW

File: packages/effects-runtime/test/__fixtures__/functional-tests/errors-in-handlers.js [hunk 1]
```diff
@@ -38,25 +32,12 @@ const asyncEjectCase = async () => {
...
+module.exports.test = async ({it, expect}) => {
     it('Should handle errors as expected when effect handlers throw', async() => {
         await expect(syncEjectCase()).rejects.toThrowError('eject');
     });
 
     it('Should handle errors as expected when effect handlers are async and throw', async () => {
         await expect(asyncEjectCase()).rejects.toThrowError('eject');
     });
-
-    it.skip('Should handle errors as expected when effect handlers are async and throw', async () => {
```
Comment (dpchamps) [inline packages/effects-runtime/test/__fixtures__/functional-tests/errors-in-handlers.js:59]: Removing this because if something like

```
setTimeout(() => {
        throw new Error('eject');
    }, 10);
```

actually _did_ throw, that would be the opposite of what was expected.

**Review by cdaringe — APPROVED** [review]

File: packages/babel-plugin-effects/src/handler-method-visitor.ts [hunk 2]
```diff
@@ -117,9 +117,13 @@ const makeHandlerMethod = (
...
         x => types.isVariableDeclaration(x) || types.isFunctionDeclaration(x)
       );
+
       if (declaration) {
         callExpressionDeclarations.add(declaration.node);
-        markPathForRemoval(declaration);
+
+        // Not the most elegant.
+        declaration.parent?.parent?.type === "Program" &&
+          markPathForRemoval(declaration);
```
Comment (cdaringe) [inline packages/babel-plugin-effects/src/handler-method-visitor.ts:126]: here's what i was looking for. what types of decls get pruned?

File: packages/effects-runtime/test/__fixtures__/functional-tests/error-handling.js [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+    });
+
+    it('Should catch exceptions at boundaries as expected', async() => {
+        await expect(errorBoundaries()).resolves.toBe(1);
+    });
+
+    it('Should bubble exceptions as expected', async () => {
+        await expect(exceptionBubbling()).rejects.toThrow('from child')
+    })
+};
```
Comment (cdaringe) [inline packages/effects-runtime/test/__fixtures__/functional-tests/error-handling.js:63]: very cheeky. nice test!

File: packages/effects-runtime/test/__fixtures__/functional-tests/errors-in-handlers.js [hunk 4]
```diff
@@ -38,16 +32,59 @@ const asyncEjectCase = async () => {
...
 
-  }handle ejectType with (e){
-      continuationEject();
+      try{
+
+          try{
+
+              try{
+
+                  try{
```
Comment (cdaringe) [inline packages/effects-runtime/test/__fixtures__/functional-tests/errors-in-handlers.js:67]: biiig giiirls dooont try, they dont try yi yi yi--_they dont try (burly voice)_

File: packages/effects-runtime/test/effects-integrations.spec.ts [hunk 5]
```diff
@@ -377,4 +377,78 @@ describe("Effect Integrations", () => {
     expect(result1).toBe(childEffectResult);
     expect(result2).toBe(childEffectResult);
   });
+
+  test("", async () => {
```
Comment (cdaringe) [inline packages/effects-runtime/test/effects-integrations.spec.ts]: `""`?

File: packages/effects-runtime/test/effects-integrations.spec.ts [hunk 6]
```diff
@@ -377,4 +377,78 @@ describe("Effect Integrations", () => {
...
+                return a;
+              }
+            })()
+          );
+        })()
+      );
+    };
+
+    const a = await catchingEject();
+    debugger;
```
Comment (cdaringe) [inline packages/effects-runtime/test/effects-integrations.spec.ts]: 😲

File: packages/babel-plugin-effects/src/handler-method-visitor.ts (hunk 2 above)
Comment (dpchamps) [reply packages/babel-plugin-effects/src/handler-method-visitor.ts:126]: Yeah, so... should we even prune at all? If we don't, there's some dead code that will be laying around.

When we're creating a handler, there is kind of a restriction at this point that `recall`s must be within the same scope of a `handle`r block. If functions are called outside of the handler block, they're hoisted inside of the handle. This obviously wouldn't work for an imported function. Hard requirement right now. 

Maybe the transform plugin should throw if that's the case?

Anyways, to answer your question, we prune a declaration if it's referenced in a handler and it's at the top-level of the program, _after_ the entire transform has been performed.

File: packages/effects-runtime/test/effects-integrations.spec.ts (hunk 5 above)
Comment (dpchamps) [reply packages/effects-runtime/test/effects-integrations.spec.ts]: oops gotta get rid of this 😮. I use the intergrations file when transpiled code is misbehaving

File: packages/babel-plugin-effects/src/handler-method-visitor.ts (hunk 2 above)
Comment (dpchamps) [reply packages/babel-plugin-effects/src/handler-method-visitor.ts:126]: We could get around this restriction by currying any function that recalls 🤔. The transformation would look like this:

```javascript
const avgJoeFn = () => {
   recall 'great.'
};
```
↓↓↓
```javascript
const wrappedAvgJoeFn = (data, resume) => function*(){
  yield resume('great')
}
```

And handlers would then call as such

```javascript
{
[myGreatHandler]*(e, resume){
   // other generated boiler plate
  return yield wrappedAvgJoeFn(e, resume)()
}
}
```

File: packages/effects-runtime/test/__fixtures__/functional-tests/errors-in-handlers.js (hunk 4 above)
Comment (dpchamps) [reply packages/effects-runtime/test/__fixtures__/functional-tests/errors-in-handlers.js:67]: As ridiculous as this test may look, I'm super happy this works now
